name: 'Check Branch 🔒'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: self-hosted
    steps:
      - name: Check Branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev. Please create a pull request to dev first, then merge dev to main."
          exit 1
